server.port=8080

# Configuracoes do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/livraria
spring.datasource.username=admin
spring.datasource.password=admin@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


spring.datasource.hikari.allow-pool-suspension=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.sql.init.mode=never
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

# Seguranca
api.security.token.secret=12345678

# Configuracoees de Email via Gmail
spring.mail.host=smtp.gmail.com
# Porta SMTP com suporte a TLS
spring.mail.port=587
spring.mail.test-connection=false
# Login
spring.mail.username=contaApiRestTest@gmail.com
spring.mail.password=sjyvlimqdemheled
# Configuracoes Adicionais
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Email de suporte
support.mail=contaApiRestTest@gmail.com


