version: "3.8"
services:
  banco:
    image: postgres
    container_name: banco_de_dados
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: livraria

#  back:
#    build:
#        context: ../
#        dockerfile: Dockerfile
#    container_name: livraria_back
#    environment:
#      - JWT_SECRET=12345678
#    env_file:
#      - livraria-back.env
#    ports:
#      - "8080:8080"
#    depends_on:
#      - banco

networks:
  default:
    driver: bridge